version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
    groups:
      python:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /docker/zeta4s-api
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
