"""Project active registrations into standalone Airflow DAG source files.

Generated files import Airflow and the Python standard library only.  The
zeta4s runtime stays in zeta4s-api and is reached through an authenticated
internal HTTP boundary.
"""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
import re
from typing import Any
from uuid import uuid4

from zeta4s.api.services.artifact_store import artifact_root
from zeta4s.prefect.runtime import load_scheduled_plan
from zeta4s.project.pools import execution_step_pool_name


GENERATED_PREFIX = "zeta4s_"


def airflow_dags_dir(home: Path) -> Path:
    return Path(os.environ.get("ZETA4S_AIRFLOW_DAGS_DIR", str(home / "airflow-dags")))


def publish_airflow_dag_sources(
    registrations: list[dict[str, Any]],
    *,
    home: Path,
    dags_dir: Path | None = None,
) -> list[Path]:
    target_dir = dags_dir or airflow_dags_dir(home)
    target_dir.mkdir(parents=True, exist_ok=True)
    desired: dict[Path, str] = {}
    for registration in registrations:
        if registration.get("scheduler_backend") != "airflow":
            continue
        for dag_spec in registration.get("dags") or []:
            source, dag_id = render_airflow_dag_source(registration, dag_spec, home=home)
            desired[target_dir / _dag_filename(dag_id)] = source

    for path, source in desired.items():
        _atomic_write(path, source)
    for stale in target_dir.glob(f"{GENERATED_PREFIX}*.py"):
        if stale not in desired:
            stale.unlink()
    return sorted(desired)


def render_airflow_dag_source(
    registration: dict[str, Any],
    dag_spec: dict[str, Any],
    *,
    home: Path,
) -> tuple[str, str]:
    project_id = str(registration["project_id"])
    artifact_id = str(registration["artifact_id"])
    profile_id = str(registration["profile_id"])
    job_id = str(dag_spec["job_id"])
    project_root = artifact_root(home, artifact_id) / "projects" / project_id
    plan, project = load_scheduled_plan(project_root, job_id)
    dag_id = str(dag_spec.get("dag_id") or f"{project_id}__{job_id}")
    spec = {
        "dag_id": dag_id,
        "project_id": project_id,
        "artifact_id": artifact_id,
        "profile_id": profile_id,
        "job_id": job_id,
        "start_date": (project.registered_at.isoformat() if project.registered_at else "2026-01-01T00:00:00+00:00"),
        "timezone": _schedule_timezone(plan.schedule, project.timezone),
        "schedule": _schedule_value(plan.schedule),
        "paused": bool(plan.schedule.paused) if plan.schedule else False,
        "tasks": [_task_spec(project_id, plan, step) for step in plan.steps],
        "terminal_step_ids": list(plan.terminal_step_ids),
    }
    payload = json.dumps(spec, ensure_ascii=False, separators=(",", ":"))
    return _SOURCE_TEMPLATE.replace("__ZETA4S_DAG_SPEC__", repr(payload)), dag_id


def _task_spec(project_id: str, plan: Any, step: Any) -> dict[str, Any]:
    retry = step.flow.retry or {}
    timeout = step.flow.timeout or {}
    when = step.step.when
    trigger_rule = step.step.join.rule if step.step.join is not None else "all_success"
    if when and when.failed:
        trigger_rule = "one_failed"
    return {
        "step_id": step.id,
        "pool": execution_step_pool_name(project_id, plan, step),
        "retries": max(0, int(retry.get("max_attempts") or 1) - 1),
        "retry_delay_seconds": max(0, int(retry.get("delay_seconds") or 0)),
        "execution_timeout_seconds": max(1, int(timeout["seconds"])) if timeout else None,
        "trigger_rule": trigger_rule,
        "upstream_ids": list(plan.upstream_ids_by_step[step.id]),
    }


def _schedule_timezone(schedule: Any, project_timezone: str) -> str:
    if schedule is None:
        return project_timezone
    return schedule.effective_timezone(project_timezone)


def _schedule_value(schedule: Any) -> str | None:
    if schedule is None:
        return None
    if schedule.cron is not None:
        return str(schedule.cron)
    return f"@continuous:{int(schedule.interval_seconds)}"


def _dag_filename(dag_id: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9_]+", "_", dag_id).strip("_")[:48] or "dag"
    digest = hashlib.sha256(dag_id.encode("utf-8")).hexdigest()[:12]
    return f"{GENERATED_PREFIX}{slug}_{digest}.py"


def _atomic_write(path: Path, source: str) -> None:
    tmp = path.with_name(f".{path.name}.{uuid4().hex}.tmp")
    try:
        tmp.write_text(source, encoding="utf-8")
        os.replace(tmp, path)
    finally:
        if tmp.exists():
            tmp.unlink()


_SOURCE_TEMPLATE = """# Generated by zeta4s-api. Do not edit.
from __future__ import annotations

from datetime import datetime, timedelta
import json
import os
import urllib.error
import urllib.request
from zoneinfo import ZoneInfo

from airflow.exceptions import AirflowSkipException
from airflow.providers.standard.operators.python import PythonOperator
from airflow.sdk import DAG, get_current_context


SPEC = json.loads(__ZETA4S_DAG_SPEC__)


def _post(path, payload):
    base_url = os.environ["ZETA4S_API_INTERNAL_URL"].rstrip("/")
    token = os.environ["ZETA4S_RUNTIME_INTERNAL_TOKEN"]
    request = urllib.request.Request(
        base_url + path,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Authorization": "Bearer " + token, "Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=86400) as response:
            return json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as error:
        detail = error.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"zeta4s-api {path} failed: HTTP {error.code}: {detail}") from error


def _run_step(step_id):
    context = get_current_context()
    dag_run = context.get("dag_run")
    conf = getattr(dag_run, "conf", None) or {}
    task_instance = context.get("task_instance") or context.get("ti")
    result = _post("/internal/v1/runtime/steps/execute", {
        "project_id": SPEC["project_id"],
        "artifact_id": SPEC["artifact_id"],
        "profile_id": SPEC["profile_id"],
        "job_id": SPEC["job_id"],
        "step_id": step_id,
        "run_id": conf.get("z4_run_id") or getattr(dag_run, "run_id", None),
        "attempt": getattr(task_instance, "try_number", 1) or 1,
        "parameters": {key: value for key, value in conf.items() if key != "z4_run_id"},
    })
    if result.get("status") == "skipped":
        raise AirflowSkipException(result.get("reason") or f"step skipped: {step_id}")
    return result


def _finalize():
    context = get_current_context()
    dag_run = context.get("dag_run")
    conf = getattr(dag_run, "conf", None) or {}
    result = _post("/internal/v1/runtime/runs/finalize", {
        "project_id": SPEC["project_id"],
        "artifact_id": SPEC["artifact_id"],
        "profile_id": SPEC["profile_id"],
        "job_id": SPEC["job_id"],
        "run_id": conf.get("z4_run_id") or getattr(dag_run, "run_id", None),
    })
    if result.get("state") == "failed":
        raise RuntimeError(f"zeta4s run failed: {result.get('run_id')}")
    return result


# Airflow derives the DAG timezone from a timezone-aware start_date, and the
# cron/interval timetable is evaluated in that timezone.
start_date = datetime.fromisoformat(SPEC["start_date"]).astimezone(ZoneInfo(SPEC["timezone"]))
schedule = SPEC["schedule"]
if isinstance(schedule, str) and schedule.startswith("@continuous:"):
    schedule = timedelta(seconds=int(schedule.split(":", 1)[1]))

with DAG(
    dag_id=SPEC["dag_id"],
    default_args={"owner": "zeta4s", "start_date": start_date},
    schedule=schedule,
    catchup=False,
    max_active_runs=1,
    is_paused_upon_creation=SPEC["paused"],
    tags=[
        "zeta4s",
        "step-graph",
        "project:" + SPEC["project_id"],
        "artifact:" + SPEC["artifact_id"],
    ],
) as dag:
    tasks = {}
    for task_spec in SPEC["tasks"]:
        timeout = task_spec["execution_timeout_seconds"]
        tasks[task_spec["step_id"]] = PythonOperator(
            task_id=task_spec["step_id"],
            python_callable=_run_step,
            op_kwargs={"step_id": task_spec["step_id"]},
            pool=task_spec["pool"],
            retries=task_spec["retries"],
            retry_delay=timedelta(seconds=task_spec["retry_delay_seconds"]),
            execution_timeout=timedelta(seconds=timeout) if timeout else None,
            trigger_rule=task_spec["trigger_rule"],
        )
    for task_spec in SPEC["tasks"]:
        for upstream_id in task_spec["upstream_ids"]:
            tasks[upstream_id] >> tasks[task_spec["step_id"]]
    finalize = PythonOperator(
        task_id="system.emit_job_success",
        python_callable=_finalize,
        trigger_rule="all_done",
    )
    for terminal_id in SPEC["terminal_step_ids"]:
        tasks[terminal_id] >> finalize
"""
